version: '3.8'

services:
  orchard-pipeline:
    build:
      context: ..  # Build from orchard/ directory, not orchard/docker/
      dockerfile: docker/Dockerfile
      platforms:
        - linux/amd64
    image: orchard-pipeline:latest
    container_name: orchard-pipeline
    volumes:
      # Local Mac paths - relative to orchard/ directory
      - ../src:/opt/orchard/src
      - /Users/matthewhooton/data/SPECULOOSPipeline:/data/SPECULOOSPipeline
      - ../results:/opt/orchard/results
    working_dir: /opt/orchard/src
    environment:
      - ORCHARD_PATH=/opt/orchard/src
      - CONDA_DEFAULT_ENV=pipeline
    command: bash -c "source /opt/anaconda/bin/activate pipeline && bash"
    stdin_open: true
    tty: true
    platform: linux/amd64