version: '2.2'

services:
  orchard-pipeline:
    image: orchard-pipeline:latest
    container_name: orchard-server
    volumes:
      - /appct/data/speculoos/orchard/src:/opt/orchard/src
      - /appct/data/SPECULOOSPipeline:/data/SPECULOOSPipeline
      - /appct/data/speculoos/orchard/results:/opt/orchard/results
    working_dir: /opt/orchard/src
    environment:
      - ORCHARD_PATH=/opt/orchard/src
      - PYTHONPATH=/opt/orchard/src
      - N_CORES=20
    # Relax container security to allow more threading
    security_opt:
      - seccomp:unconfined
    ulimits:
      nproc: 65536
      nofile: 65536
    command: bash
    stdin_open: true
    tty: true
    restart: unless-stopped